### ISSUE TITLE
Multiple Main Files JSON

### ISSUE THREAD

**Issue by pawelgola** [jonycheung/deadsimple-less-watch-compiler#21]
Is it possible to specifiy mutliple main files within the config.json file?

**Comment by jonycheung** [comment]
hi @pawelgola instead of multiple main file, I've made it so that it maps the files and their dependencies within a given watch folder:
Example:
* main1.less includes `./include/_style1.less`
* main2.less includes `./include/_style1.less` and `./include/_style2.less`

If `./include/_style2.less` updates, main2.less gets compiled.
If `./include/_style1.less` updates, main1.less and main2.less get compiled.

Let me know if you have issues with this.
